export const Styles = {
  Container: 'sample-items-container',
  Section: 'sample-items-section',
  Header: 'sample-items-header',
  LoadingBoard: 'sample-items-loading-board mt-board',
  LoadingContent: 'sample-items-loading-content',
  LoadingIcon: 'sample-items-loading-icon',
  LoadingMessage: 'sample-items-loading-message',
  Navigator: 'sample-items-navigator',
  NavigatorButton: 'sample-items-navigator-button',
  NavigatorButtonSelected: 'sample-items-navigator-button-selected',
  NavigatorButtonIdle: 'sample-items-navigator-button-idle',
  QuestionCard: 'sample-items-question-card mt-board',
  QuestionHeader: 'sample-items-question-header',
  QuestionHeaderLayout: 'sample-items-question-header-layout',
  QuestionIdentity: 'sample-items-question-identity',
  QuestionPosition: 'sample-items-question-position',
  QuestionMetaTitle: 'sample-items-question-meta-title',
  QuestionMetaInstruction: 'sample-items-question-meta-instruction',
  QuestionId: 'sample-items-question-id',
  QuestionBody: 'sample-items-question-body',
  QuestionCopy: 'sample-items-question-copy',
  AnswerGrid: 'sample-items-answer-grid',
  AnswerChoice: 'sample-items-answer-choice',
  AnswerChoiceSelected: 'sample-items-answer-choice-selected',
  AnswerChoiceIdle: 'sample-items-answer-choice-idle',
  AnswerLabel: 'sample-items-answer-label',
  AnswerLabelSelected: 'sample-items-answer-label-selected',
  AnswerExpression: 'sample-items-answer-expression',
  QuestionActions: 'sample-items-question-actions',
  QuestionHint: 'sample-items-question-hint',
  Feedback: 'sample-items-feedback',
  CoachingCard: 'sample-items-coaching-card',
  CoachingLabel: 'sample-items-coaching-label',
  CoachingMessage: 'sample-items-coaching-message',
  CoachingActions: 'sample-items-coaching-actions'
} as const

export type Style = typeof Styles[keyof typeof Styles]
