/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RunAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sample-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSampleQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sample-questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSampleQuestionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgentRequest: {
            model: string;
            instructions: string;
            prompt: string;
            history: components["schemas"]["TurnDto"][];
        };
        AgentResponse: {
            text: string;
            model: string;
            /** Format: int32 */
            inputTokens: number | string;
            /** Format: int32 */
            outputTokens: number | string;
        };
        /** @enum {unknown} */
        AgentRole: "user" | "assistant";
        AnswerChoiceResponse: {
            id: string;
            labelSpan: components["schemas"]["TokenSpanResponse"];
            contentSpan: components["schemas"]["TokenSpanResponse"];
        };
        DerivationOperationResponse: components["schemas"]["DerivationOperationResponseScaleByResponse"] | components["schemas"]["DerivationOperationResponseIncrementByResponse"];
        DerivationOperationResponseIncrementByResponse: {
            /** @enum {string} */
            type?: "incrementBy";
            anchoredByPhraseId: string;
            incrementId: string;
        };
        DerivationOperationResponseScaleByResponse: {
            /** @enum {string} */
            type?: "scaleBy";
            anchoredByPhraseId: string;
            scaleFactorId: string;
        };
        FoundryDeploymentResponse: {
            name: string;
            displayName: string;
            vendor: components["schemas"]["VendorName"];
        };
        LatentMathProvenanceResponse: {
            origin: string;
            anchorPhraseIds: string[];
            sourceEntityIds: string[];
            sourceLatentMathIds: string[];
        };
        LatentMathResponse: components["schemas"]["LatentMathResponseDerivedScalarResponse"] | components["schemas"]["LatentMathResponseDerivedExpressionResponse"];
        LatentMathResponseDerivedExpressionResponse: {
            /** @enum {string} */
            type?: "derivedExpression";
            id: string;
            meaning: string;
            mathObjectId: string;
            provenance: components["schemas"]["LatentMathProvenanceResponse"];
        };
        LatentMathResponseDerivedScalarResponse: {
            /** @enum {string} */
            type?: "derivedScalar";
            id: string;
            meaning: string;
            /** Format: double */
            value: number | string;
            provenance: components["schemas"]["LatentMathProvenanceResponse"];
        };
        ModelMessage: {
            message: string;
            model: string;
            role: components["schemas"]["AgentRole"];
        };
        PhraseSpanResponse: {
            id: string;
            span: components["schemas"]["TokenSpanResponse"];
        };
        PracticeItemResponse: {
            id: string;
            text: components["schemas"]["TextStructureResponse"];
            semantics: components["schemas"]["SemanticModelResponse"];
            answers: components["schemas"]["AnswerChoiceResponse"][];
            correctAnswerId: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        SemanticEdgeResponse: components["schemas"]["SemanticEdgeResponseSelectsElementResponse"] | components["schemas"]["SemanticEdgeResponseRefersToResponse"] | components["schemas"]["SemanticEdgeResponseDerivesFromResponse"] | components["schemas"]["SemanticEdgeResponseRequestsValueResponse"] | components["schemas"]["SemanticEdgeResponseRequestsOperationResponse"];
        SemanticEdgeResponseDerivesFromResponse: {
            /** @enum {string} */
            type?: "derivesFrom";
            targetEntityId: string;
            sourceEntityId: string;
            operationsInBuildOrder: components["schemas"]["DerivationOperationResponse"][];
        };
        SemanticEdgeResponseRefersToResponse: {
            /** @enum {string} */
            type?: "refersTo";
            anaphorPhraseId: string;
            referentId: string;
        };
        SemanticEdgeResponseRequestsOperationResponse: {
            /** @enum {string} */
            type?: "requestsOperation";
            requestedByPhraseId: string;
            operation: string;
            operandEntityId: string;
        };
        SemanticEdgeResponseRequestsValueResponse: {
            /** @enum {string} */
            type?: "requestsValue";
            requestedByPhraseId: string;
            requestedEntityId: string;
        };
        SemanticEdgeResponseSelectsElementResponse: {
            /** @enum {string} */
            type?: "selectsElement";
            quantityId: string;
            collectionId: string;
            selector: string;
            anchoredByPhraseId: string;
        };
        SemanticEntityResponse: components["schemas"]["SemanticEntityResponseVariableQuantityResponse"] | components["schemas"]["SemanticEntityResponseDerivedQuantityResponse"] | components["schemas"]["SemanticEntityResponseOrderedSetResponse"];
        SemanticEntityResponseDerivedQuantityResponse: {
            /** @enum {string} */
            type?: "derivedQuantity";
            id: string;
            declaredBySentenceId: string;
        };
        SemanticEntityResponseOrderedSetResponse: {
            /** @enum {string} */
            type?: "orderedSet";
            id: string;
            declaredByPhraseId: string;
            /** Format: int32 */
            cardinality: number | string;
            domain: string;
        };
        SemanticEntityResponseVariableQuantityResponse: {
            /** @enum {string} */
            type?: "variableQuantity";
            id: string;
            symbolId: string;
            name: string;
            declaredByTokenId: string;
        };
        SemanticModelResponse: {
            entities: components["schemas"]["SemanticEntityResponse"][];
            edges: components["schemas"]["SemanticEdgeResponse"][];
            latentFacts: components["schemas"]["LatentMathResponse"][];
        };
        SentenceSpanResponse: {
            id: string;
            span: components["schemas"]["TokenSpanResponse"];
        };
        TextStructureResponse: {
            tokens: components["schemas"]["TextTokenResponse"][];
            sentences: components["schemas"]["SentenceSpanResponse"][];
            phrases: components["schemas"]["PhraseSpanResponse"][];
        };
        TextTokenResponse: {
            id: string;
            /** Format: int32 */
            index: number | string;
            surface: string;
            kind: string;
        };
        TokenSpanResponse: {
            /** Format: int32 */
            start: number | string;
            /** Format: int32 */
            length: number | string;
        };
        TurnDto: components["schemas"]["UserMessage"] | components["schemas"]["ModelMessage"];
        UserMessage: {
            message: string;
            role: components["schemas"]["AgentRole"];
        };
        /** @enum {unknown} */
        VendorName: "anthropic" | "openAI" | "deepSeek";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundryDeploymentResponse"][];
                };
            };
        };
    };
    RunAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetSampleQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeItemResponse"][];
                };
            };
        };
    };
    GetSampleQuestionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeItemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
