/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RunAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/coach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CoachAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sample-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSampleQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sample-questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSampleQuestionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPracticeItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPracticeItemById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StartAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAttempt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CheckAttemptAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scaffolds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetScaffolds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scaffolds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetScaffoldById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/scaffold-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StartScaffoldSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scaffold-sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetScaffoldSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scaffold-sessions/{sessionId}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CheckScaffoldSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgentRequest: {
            model: string;
            instructions: string;
            prompt: string;
            history: components["schemas"]["TurnDto"][];
        };
        AgentResponse: {
            text: string;
            model: string;
            /** Format: int32 */
            inputTokens: number | string;
            /** Format: int32 */
            outputTokens: number | string;
        };
        /** @enum {unknown} */
        AgentRole: "user" | "assistant";
        AnswerChoiceResponse: {
            id: string;
            labelSpan: components["schemas"]["TokenSpanResponse"];
            labelCharacterSpan: components["schemas"]["CharacterSpanResponse"];
            contentSpan: components["schemas"]["TokenSpanResponse"];
            contentCharacterSpan: components["schemas"]["CharacterSpanResponse"];
        };
        AnswerMathBindingResponse: {
            answerChoiceId: string;
            mathObjectId: string;
        };
        AttemptPhaseResponse: components["schemas"]["AttemptPhaseResponseBeforeCheckResponse"] | components["schemas"]["AttemptPhaseResponseAfterIncorrectCheckResponse"] | components["schemas"]["AttemptPhaseResponseAfterCorrectCheckResponse"];
        AttemptPhaseResponseAfterCorrectCheckResponse: {
            /** @enum {string} */
            type?: "afterCorrectCheck";
            selectedAnswerId: string;
        };
        AttemptPhaseResponseAfterIncorrectCheckResponse: {
            /** @enum {string} */
            type?: "afterIncorrectCheck";
            selectedAnswerId: string;
            misconceptionCode: string;
            purpose: string;
            route: components["schemas"]["CoachingRouteResponse"];
            /** Format: int32 */
            routeStreak: number | string;
            hintLevel: string;
        };
        AttemptPhaseResponseBeforeCheckResponse: {
            /** @enum {string} */
            type?: "beforeCheck";
        };
        AttemptProjectionResponse: {
            attemptId: string;
            practiceItemId: string;
            /** Format: int32 */
            checkCount: number | string;
            phase: components["schemas"]["AttemptPhaseResponse"];
            coachingButton: components["schemas"]["CoachingButtonResponse"];
        };
        CharacterSpanResponse: {
            /** Format: int32 */
            start: number | string;
            /** Format: int32 */
            length: number | string;
        };
        CheckAnswerRequest: {
            selectedAnswerId: string;
        };
        CoachingButtonResponse: components["schemas"]["CoachingButtonResponseVisibleCoachingButtonResponse"] | components["schemas"]["CoachingButtonResponseHiddenCoachingButtonResponse"];
        CoachingButtonResponseHiddenCoachingButtonResponse: {
            /** @enum {string} */
            type?: "hidden";
        };
        CoachingButtonResponseVisibleCoachingButtonResponse: {
            /** @enum {string} */
            type?: "visible";
            label: string;
        };
        CoachingRouteResponse: components["schemas"]["CoachingRouteResponseScaffoldEntryRouteResponse"] | components["schemas"]["CoachingRouteResponseNoScaffoldAuthoredRouteResponse"];
        CoachingRouteResponseNoScaffoldAuthoredRouteResponse: {
            /** @enum {string} */
            type?: "noScaffoldAuthored";
        };
        CoachingRouteResponseScaffoldEntryRouteResponse: {
            /** @enum {string} */
            type?: "scaffoldEntry";
            scaffoldId: string;
            entryStepId: string;
        };
        CoachMoveResponse: components["schemas"]["CoachMoveResponseAskReadingQuestionResponse"] | components["schemas"]["CoachMoveResponseDiagnoseDifferenceResponse"] | components["schemas"]["CoachMoveResponseSuggestScaffoldResponse"] | components["schemas"]["CoachMoveResponseExplainWhyResponse"];
        CoachMoveResponseAskReadingQuestionResponse: {
            /** @enum {string} */
            type?: "askReadingQuestion";
            message: string;
            focusPhraseIds: string[];
        };
        CoachMoveResponseDiagnoseDifferenceResponse: {
            /** @enum {string} */
            type?: "diagnoseDifference";
            message: string;
            focusPhraseIds: string[];
        };
        CoachMoveResponseExplainWhyResponse: {
            /** @enum {string} */
            type?: "explainWhy";
            provenanceFactIds: string[];
            message: string;
            focusPhraseIds: string[];
        };
        CoachMoveResponseSuggestScaffoldResponse: {
            /** @enum {string} */
            type?: "suggestScaffold";
            suggestedStepId: string;
            message: string;
            focusPhraseIds: string[];
        };
        /** @enum {unknown} */
        CoachTurnEvent: "helpRequested" | "diagnosisRequested" | "explainCorrect";
        CoachTurnRequest: {
            event: components["schemas"]["CoachTurnEvent"];
        };
        CoachTurnResponse: {
            move: components["schemas"]["CoachMoveResponse"];
        };
        DerivationOperationResponse: components["schemas"]["DerivationOperationResponseScaleByResponse"] | components["schemas"]["DerivationOperationResponseIncrementByResponse"];
        DerivationOperationResponseIncrementByResponse: {
            /** @enum {string} */
            type?: "incrementBy";
            anchoredByPhraseId: string;
            incrementId: string;
        };
        DerivationOperationResponseScaleByResponse: {
            /** @enum {string} */
            type?: "scaleBy";
            anchoredByPhraseId: string;
            scaleFactorId: string;
        };
        FoundryDeploymentResponse: {
            name: string;
            displayName: string;
            vendor: components["schemas"]["VendorName"];
        };
        InstructionalBindingResponse: {
            semanticEntityId: string;
            /** Format: int32 */
            value: number | string;
        };
        JsonElement: unknown;
        LatentMathProvenanceResponse: {
            origin: string;
            anchorPhraseIds: string[];
            sourceEntityIds: string[];
            sourceLatentMathIds: string[];
        };
        LatentMathResponse: components["schemas"]["LatentMathResponseDerivedScalarResponse"] | components["schemas"]["LatentMathResponseDerivedExpressionResponse"];
        LatentMathResponseDerivedExpressionResponse: {
            /** @enum {string} */
            type?: "derivedExpression";
            id: string;
            meaning: string;
            mathObjectId: string;
            provenance: components["schemas"]["LatentMathProvenanceResponse"];
        };
        LatentMathResponseDerivedScalarResponse: {
            /** @enum {string} */
            type?: "derivedScalar";
            id: string;
            meaning: string;
            /** Format: double */
            value: number | string;
            provenance: components["schemas"]["LatentMathProvenanceResponse"];
        };
        LearnerActionResponse: components["schemas"]["LearnerActionResponseMatchEquivalentLengthActionResponse"] | components["schemas"]["LearnerActionResponseClassifyByFitActionResponse"] | components["schemas"]["LearnerActionResponseNameFitClassificationActionResponse"] | components["schemas"]["LearnerActionResponseTraverseAllGapsActionResponse"] | components["schemas"]["LearnerActionResponseJoinQuantitiesActionResponse"] | components["schemas"]["LearnerActionResponseEnterScalarActionResponse"] | components["schemas"]["LearnerActionResponseBuildExpressionActionResponse"] | components["schemas"]["LearnerActionResponseSelectAnswerChoiceActionResponse"];
        LearnerActionResponseBuildExpressionActionResponse: {
            /** @enum {string} */
            type?: "buildExpression";
        };
        LearnerActionResponseClassifyByFitActionResponse: {
            /** @enum {string} */
            type?: "classifyByFit";
        };
        LearnerActionResponseEnterScalarActionResponse: {
            /** @enum {string} */
            type?: "enterScalar";
            reading: string;
        };
        LearnerActionResponseJoinQuantitiesActionResponse: {
            /** @enum {string} */
            type?: "joinQuantities";
        };
        LearnerActionResponseMatchEquivalentLengthActionResponse: {
            /** @enum {string} */
            type?: "matchEquivalentLength";
        };
        LearnerActionResponseNameFitClassificationActionResponse: {
            /** @enum {string} */
            type?: "nameFitClassification";
            classification: string;
        };
        LearnerActionResponseSelectAnswerChoiceActionResponse: {
            /** @enum {string} */
            type?: "selectAnswerChoice";
        };
        LearnerActionResponseTraverseAllGapsActionResponse: {
            /** @enum {string} */
            type?: "traverseAllGaps";
        };
        LengthSourceResponse: components["schemas"]["LengthSourceResponseLiteralLengthResponse"] | components["schemas"]["LengthSourceResponseLatentLengthReferenceResponse"];
        LengthSourceResponseLatentLengthReferenceResponse: {
            /** @enum {string} */
            type?: "latentLengthReference";
            latentMathId: string;
        };
        LengthSourceResponseLiteralLengthResponse: {
            /** @enum {string} */
            type?: "literalLength";
            /** Format: int32 */
            value: number | string;
        };
        MathematicsResponse: {
            objects: components["schemas"]["MathObjectResponse"][];
            textBindings: components["schemas"]["MathTextBindingResponse"][];
        };
        MathNodeResponse: {
            id: string;
            kind: string;
            value: null | string;
            childNodeIds: string[];
        };
        MathObjectResponse: {
            id: string;
            rootNodeId: string;
            nodes: components["schemas"]["MathNodeResponse"][];
        };
        MathTextBindingResponse: {
            mathObjectId: string;
            mathNodeId: null | string;
            characterSpan: components["schemas"]["CharacterSpanResponse"];
        };
        ModelMessage: {
            message: string;
            model: string;
            role: components["schemas"]["AgentRole"];
        };
        PhraseSpanResponse: {
            id: string;
            span: components["schemas"]["TokenSpanResponse"];
            characterSpan: components["schemas"]["CharacterSpanResponse"];
        };
        PracticeItemPromptResponse: {
            id: string;
            text: components["schemas"]["TextStructureResponse"];
            semantics: components["schemas"]["PromptSemanticModelResponse"];
            mathematics: components["schemas"]["MathematicsResponse"];
            interaction: components["schemas"]["PromptMultipleChoiceInteractionResponse"];
        };
        PracticeItemResponse: {
            id: string;
            text: components["schemas"]["TextStructureResponse"];
            semantics: components["schemas"]["SemanticModelResponse"];
            mathematics: components["schemas"]["MathematicsResponse"];
            interaction: components["schemas"]["QuestionInteractionResponse"];
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        PromptMultipleChoiceInteractionResponse: {
            answers: components["schemas"]["AnswerChoiceResponse"][];
            answerMathBindings: components["schemas"]["AnswerMathBindingResponse"][];
        };
        PromptSemanticModelResponse: {
            entities: components["schemas"]["SemanticEntityResponse"][];
            edges: components["schemas"]["SemanticEdgeResponse"][];
        };
        QuantityReferenceResponse: components["schemas"]["QuantityReferenceResponseSemanticQuantityReferenceResponse"] | components["schemas"]["QuantityReferenceResponseLatentExpressionReferenceResponse"];
        QuantityReferenceResponseLatentExpressionReferenceResponse: {
            /** @enum {string} */
            type?: "latentExpressionReference";
            latentMathId: string;
        };
        QuantityReferenceResponseSemanticQuantityReferenceResponse: {
            /** @enum {string} */
            type?: "semanticQuantityReference";
            semanticEntityId: string;
        };
        QuestionInteractionResponse: components["schemas"]["QuestionInteractionResponseMultipleChoiceInteractionResponse"];
        QuestionInteractionResponseMultipleChoiceInteractionResponse: {
            /** @enum {string} */
            type?: "multipleChoice";
            answers: components["schemas"]["AnswerChoiceResponse"][];
            answerMathBindings: components["schemas"]["AnswerMathBindingResponse"][];
            correctAnswerId: string;
        };
        ScaffoldLastCheckResponse: {
            stepId: string;
            satisfied: boolean;
        };
        ScaffoldLearnerResourceResponse: components["schemas"]["ScaffoldLearnerResourceResponseScaffoldLearnerRodResourceResponse"] | components["schemas"]["ScaffoldLearnerResourceResponseScaffoldLearnerRodSeriesResourceResponse"];
        ScaffoldLearnerResourceResponseScaffoldLearnerRodResourceResponse: {
            /** @enum {string} */
            type?: "rodResource";
            id: string;
            /** Format: int32 */
            length: number | string;
            multiplicity: string;
            role: string;
        };
        ScaffoldLearnerResourceResponseScaffoldLearnerRodSeriesResourceResponse: {
            /** @enum {string} */
            type?: "rodSeriesResource";
            id: string;
            lengths: (number | string)[];
        };
        ScaffoldLearnerStepResponse: {
            id: string;
            prompt: components["schemas"]["ScaffoldPromptResponse"];
            scene: components["schemas"]["ScaffoldSceneResponse"];
            action: components["schemas"]["LearnerActionResponse"];
        };
        ScaffoldPhaseResponse: {
            id: string;
            purpose: string;
            steps: components["schemas"]["ScaffoldStepResponse"][];
        };
        ScaffoldPromptResponse: {
            text: string;
            focusPhraseIds: string[];
        };
        ScaffoldResourceResponse: components["schemas"]["ScaffoldResourceResponseRodResourceResponse"] | components["schemas"]["ScaffoldResourceResponseRodSeriesResourceResponse"];
        ScaffoldResourceResponseRodResourceResponse: {
            /** @enum {string} */
            type?: "rodResource";
            id: string;
            length: components["schemas"]["LengthSourceResponse"];
            multiplicity: string;
            role: string;
        };
        ScaffoldResourceResponseRodSeriesResourceResponse: {
            /** @enum {string} */
            type?: "rodSeriesResource";
            id: string;
            lengths: (number | string)[];
        };
        ScaffoldResponse: {
            id: string;
            practiceItemId: string;
            resources: components["schemas"]["ScaffoldResourceResponse"][];
            phases: components["schemas"]["ScaffoldPhaseResponse"][];
        };
        ScaffoldSceneResponse: components["schemas"]["ScaffoldSceneResponseRodEquivalenceSceneResponse"] | components["schemas"]["ScaffoldSceneResponseRodMeasurementSceneResponse"] | components["schemas"]["ScaffoldSceneResponseRodGapSceneResponse"] | components["schemas"]["ScaffoldSceneResponseQuantityJoinSceneResponse"] | components["schemas"]["ScaffoldSceneResponseAnswerChoiceSceneResponse"];
        ScaffoldSceneResponseAnswerChoiceSceneResponse: {
            /** @enum {string} */
            type?: "answerChoiceScene";
        };
        ScaffoldSceneResponseQuantityJoinSceneResponse: {
            /** @enum {string} */
            type?: "quantityJoinScene";
            parts: components["schemas"]["QuantityReferenceResponse"][];
            bindings: components["schemas"]["InstructionalBindingResponse"][];
            showSizedTarget: boolean;
        };
        ScaffoldSceneResponseRodEquivalenceSceneResponse: {
            /** @enum {string} */
            type?: "rodEquivalenceScene";
            unitRodId: string;
            probeRodId: string;
        };
        ScaffoldSceneResponseRodGapSceneResponse: {
            /** @enum {string} */
            type?: "rodGapScene";
            stepRodId: string;
            classificationStepId: string;
            includedOutcome: string;
        };
        ScaffoldSceneResponseRodMeasurementSceneResponse: {
            /** @enum {string} */
            type?: "rodMeasurementScene";
            probeRodId: string;
            spanSeriesId: string;
        };
        ScaffoldSessionResponse: {
            sessionId: string;
            attemptId: string;
            practiceItemId: string;
            scaffoldId: string;
            entryStepId: string;
            /** Format: int32 */
            checkCount: number | string;
            /** Format: int32 */
            completedStepCount: number | string;
            /** Format: int32 */
            totalStepCount: number | string;
            resources: components["schemas"]["ScaffoldLearnerResourceResponse"][];
            state: components["schemas"]["ScaffoldSessionStateResponse"];
            lastCheck: null | components["schemas"]["ScaffoldLastCheckResponse"];
        };
        ScaffoldSessionStateResponse: components["schemas"]["ScaffoldSessionStateResponseActiveScaffoldSessionResponse"] | components["schemas"]["ScaffoldSessionStateResponseCompletedScaffoldSessionResponse"];
        ScaffoldSessionStateResponseActiveScaffoldSessionResponse: {
            /** @enum {string} */
            type?: "active";
            currentStep: components["schemas"]["ScaffoldLearnerStepResponse"];
        };
        ScaffoldSessionStateResponseCompletedScaffoldSessionResponse: {
            /** @enum {string} */
            type?: "completed";
        };
        ScaffoldStepResponse: {
            id: string;
            prompt: components["schemas"]["ScaffoldPromptResponse"];
            scene: components["schemas"]["StepSceneResponse"];
            action: components["schemas"]["LearnerActionResponse"];
            successCheck: components["schemas"]["SuccessCheckResponse"];
        };
        SemanticEdgeResponse: components["schemas"]["SemanticEdgeResponseSelectsElementResponse"] | components["schemas"]["SemanticEdgeResponseRefersToResponse"] | components["schemas"]["SemanticEdgeResponseDerivesFromResponse"] | components["schemas"]["SemanticEdgeResponseRequestsValueResponse"] | components["schemas"]["SemanticEdgeResponseRequestsOperationResponse"];
        SemanticEdgeResponseDerivesFromResponse: {
            /** @enum {string} */
            type?: "derivesFrom";
            targetEntityId: string;
            sourceEntityId: string;
            operationsInBuildOrder: components["schemas"]["DerivationOperationResponse"][];
        };
        SemanticEdgeResponseRefersToResponse: {
            /** @enum {string} */
            type?: "refersTo";
            anaphorPhraseId: string;
            referentId: string;
        };
        SemanticEdgeResponseRequestsOperationResponse: {
            /** @enum {string} */
            type?: "requestsOperation";
            requestedByPhraseId: string;
            operation: string;
            operandEntityId: string;
        };
        SemanticEdgeResponseRequestsValueResponse: {
            /** @enum {string} */
            type?: "requestsValue";
            requestedByPhraseId: string;
            requestedEntityId: string;
        };
        SemanticEdgeResponseSelectsElementResponse: {
            /** @enum {string} */
            type?: "selectsElement";
            quantityId: string;
            collectionId: string;
            selector: string;
            anchoredByPhraseId: string;
        };
        SemanticEntityResponse: components["schemas"]["SemanticEntityResponseVariableQuantityResponse"] | components["schemas"]["SemanticEntityResponseDerivedQuantityResponse"] | components["schemas"]["SemanticEntityResponseOrderedSetResponse"];
        SemanticEntityResponseDerivedQuantityResponse: {
            /** @enum {string} */
            type?: "derivedQuantity";
            id: string;
            declaredBySentenceId: string;
        };
        SemanticEntityResponseOrderedSetResponse: {
            /** @enum {string} */
            type?: "orderedSet";
            id: string;
            declaredByPhraseId: string;
            /** Format: int32 */
            cardinality: number | string;
            domain: string;
        };
        SemanticEntityResponseVariableQuantityResponse: {
            /** @enum {string} */
            type?: "variableQuantity";
            id: string;
            symbolId: string;
            name: string;
            declaredByTokenId: string;
        };
        SemanticModelResponse: {
            entities: components["schemas"]["SemanticEntityResponse"][];
            edges: components["schemas"]["SemanticEdgeResponse"][];
            latentFacts: components["schemas"]["LatentMathResponse"][];
        };
        SentenceSpanResponse: {
            id: string;
            span: components["schemas"]["TokenSpanResponse"];
            characterSpan: components["schemas"]["CharacterSpanResponse"];
        };
        StartAttemptRequest: {
            practiceItemId: string;
        };
        StepSceneResponse: components["schemas"]["StepSceneResponseFreshSceneResponse"] | components["schemas"]["StepSceneResponseContinuedSceneResponse"];
        StepSceneResponseContinuedSceneResponse: {
            /** @enum {string} */
            type?: "continuedScene";
            sourceStepId: string;
            access: string;
        };
        StepSceneResponseFreshSceneResponse: {
            /** @enum {string} */
            type?: "freshScene";
            definition: components["schemas"]["ScaffoldSceneResponse"];
        };
        SuccessCheckResponse: components["schemas"]["SuccessCheckResponseLengthsAreEquivalentCheckResponse"] | components["schemas"]["SuccessCheckResponseMatchesComputedFitCheckResponse"] | components["schemas"]["SuccessCheckResponseMatchesIntegerDomainCheckResponse"] | components["schemas"]["SuccessCheckResponseAllGapsTraversedCheckResponse"] | components["schemas"]["SuccessCheckResponseMatchesPartCompositionCheckResponse"] | components["schemas"]["SuccessCheckResponseMatchesLatentScalarCheckResponse"] | components["schemas"]["SuccessCheckResponseMatchesLatentExpressionCheckResponse"] | components["schemas"]["SuccessCheckResponseMatchesCorrectAnswerCheckResponse"];
        SuccessCheckResponseAllGapsTraversedCheckResponse: {
            /** @enum {string} */
            type?: "allGapsTraversed";
            requiredResourceId: string;
        };
        SuccessCheckResponseLengthsAreEquivalentCheckResponse: {
            /** @enum {string} */
            type?: "lengthsAreEquivalent";
        };
        SuccessCheckResponseMatchesComputedFitCheckResponse: {
            /** @enum {string} */
            type?: "matchesComputedFit";
        };
        SuccessCheckResponseMatchesCorrectAnswerCheckResponse: {
            /** @enum {string} */
            type?: "matchesCorrectAnswer";
        };
        SuccessCheckResponseMatchesIntegerDomainCheckResponse: {
            /** @enum {string} */
            type?: "matchesIntegerDomain";
            classification: string;
            domain: string;
        };
        SuccessCheckResponseMatchesLatentExpressionCheckResponse: {
            /** @enum {string} */
            type?: "matchesLatentExpression";
            expectedExpressionId: string;
        };
        SuccessCheckResponseMatchesLatentScalarCheckResponse: {
            /** @enum {string} */
            type?: "matchesLatentScalar";
            expectedValueId: string;
            reading: string;
        };
        SuccessCheckResponseMatchesPartCompositionCheckResponse: {
            /** @enum {string} */
            type?: "matchesPartComposition";
        };
        TextStructureResponse: {
            sourceText: string;
            tokens: components["schemas"]["TextTokenResponse"][];
            sentences: components["schemas"]["SentenceSpanResponse"][];
            phrases: components["schemas"]["PhraseSpanResponse"][];
        };
        TextTokenResponse: {
            id: string;
            /** Format: int32 */
            index: number | string;
            surface: string;
            kind: string;
            characterSpan: components["schemas"]["CharacterSpanResponse"];
        };
        TokenSpanResponse: {
            /** Format: int32 */
            start: number | string;
            /** Format: int32 */
            length: number | string;
        };
        TurnDto: components["schemas"]["UserMessage"] | components["schemas"]["ModelMessage"];
        UserMessage: {
            message: string;
            role: components["schemas"]["AgentRole"];
        };
        /** @enum {unknown} */
        VendorName: "anthropic" | "openAI" | "deepSeek";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundryDeploymentResponse"][];
                };
            };
        };
    };
    RunAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CoachAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachTurnRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachTurnResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Client Closed Request */
            499: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetSampleQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeItemResponse"][];
                };
            };
        };
    };
    GetSampleQuestionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeItemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetPracticeItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeItemPromptResponse"][];
                };
            };
        };
    };
    GetPracticeItemById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeItemPromptResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    StartAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartAttemptRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptProjectionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptProjectionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CheckAttemptAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckAnswerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptProjectionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetScaffolds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScaffoldResponse"][];
                };
            };
        };
    };
    GetScaffoldById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScaffoldResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StartScaffoldSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScaffoldSessionResponse"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScaffoldSessionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetScaffoldSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScaffoldSessionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CheckScaffoldSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JsonElement"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScaffoldSessionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
