import { test, expect } from '@playwright/test'

test('grid renders, orbits, changes view, and fits a narrow viewport', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/dev/grid-3d')
  await expect(page.getByRole('region', { name: '3D grid', exact: true })).toHaveAttribute('data-ready', 'true', { timeout: 30_000 })
  const canvas = page.locator('[data-role=viewport]')
  await expect(canvas).toBeVisible()
  const initial = await canvas.screenshot()
  const box = await canvas.boundingBox()
  if (!box) throw new Error('Grid has no visible bounds')
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width / 2 + 90, box.y + box.height / 2 + 30, { steps: 8 })
  await page.mouse.up()
  expect((await canvas.screenshot()).equals(initial)).toBe(true)
  await page.getByRole('button', { name: 'Adjust view' }).click()
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width / 2 + 90, box.y + box.height / 2 + 30, { steps: 8 })
  await page.mouse.up()
  expect((await canvas.screenshot()).equals(initial)).toBe(false)
  await page.getByRole('button', { name: 'Reset view' }).click()
  await expect(page.getByRole('button', { name: 'Adjust view' })).toHaveAttribute('aria-pressed', 'false')
  expect((await canvas.screenshot()).equals(initial)).toBe(true)
  await page.getByRole('button', { name: 'Top view' }).click()
  expect((await canvas.screenshot()).equals(initial)).toBe(false)
  await page.getByRole('button', { name: 'Reset view' }).click()
  await canvas.screenshot({ path: testInfo.outputPath('grid-3d.png') })
  await page.setViewportSize({ width: 390, height: 740 })
  await expect.poll(async () => (await canvas.boundingBox())?.width).toBeLessThan(390)
  await expect(page.getByRole('alert')).toHaveCount(0)
  expect(errors).toEqual([])
})
