import { readFile } from 'node:fs/promises'
import type { Locator } from '@playwright/test'
import { test, expect, type Playground } from './fixtures/playground-fixture'
import { levelDocumentSchema } from '../../app/components/playground/files/level-document.schema'
async function snapshot(p: Playground, panel: Locator) {
  return Promise.all((await panel.locator('[data-piece-id]').all()).map(async train => ({
    id: await train.getAttribute('data-piece-id'), geometry: await p.geometry(train),
    parts: await Promise.all((await train.locator('.train-part').all()).map(async part => ({ value: await part.getAttribute('data-part-value'), geometry: await p.geometry(part) }))),
  })))
}
for (const kind of ['Bar', 'Array', 'Fraction', 'MathTabla'] as const) {
  test(`${kind} level file round trip preserves ordered snapshots, metadata, goals and IDs`, async ({ playground: p, page }, info) => {
    const panel = await p.show(kind)
    const capture = panel.getByRole('button', { name: 'Capture step', exact: true })
    const controls = panel.getByRole('group', { name: 'Authoring steps', exact: true })
    await p.add(kind, 'two')
    const first = await snapshot(p, panel)
    await capture.click()
    await panel.getByRole('textbox', { name: 'Title', exact: true }).fill('First arrangement')
    await panel.getByRole('textbox', { name: 'Prompt', exact: true }).fill('First instruction.\nExplain your answer.')
    await panel.getByRole('button', { name: 'Add condition', exact: true }).click()
    await panel.getByRole('combobox', { name: 'Condition type', exact: true }).selectOption('occupied-area')
    await panel.getByLabel('Cells', { exact: true }).fill('2')
    await panel.getByRole('button', { name: 'Apply goal', exact: true }).click()
    await p.add(kind, 'three')
    const second = await snapshot(p, panel)
    await capture.click()
    await panel.getByRole('textbox', { name: 'Title', exact: true }).fill('Second arrangement')
    await panel.getByRole('textbox', { name: 'Prompt', exact: true }).fill('Second instruction.')
    await panel.getByRole('button', { name: 'Add condition', exact: true }).click()
    await panel.getByRole('combobox', { name: 'Condition type', exact: true }).selectOption('region-total')
    await panel.getByLabel('Value', { exact: true }).fill('5')
    await panel.getByRole('button', { name: 'Apply goal', exact: true }).click()
    await panel.getByRole('button', { name: 'Move earlier', exact: true }).click()
    const pending = page.waitForEvent('download')
    await panel.getByRole('button', { name: 'Export level', exact: true }).click()
    const download = await pending
    const path = info.outputPath(download.suggestedFilename())
    await download.saveAs(path)
    const document = levelDocumentSchema.parse(JSON.parse(await readFile(path, 'utf8')))
    expect(document.steps.map(step => step.id)).toEqual(['step-2', 'step-1'])
    expect(document.steps.map(step => step.goal?.conditions[0]?.type)).toEqual(['region-total', 'occupied-area'])
    await page.reload()
    await expect(p.panel('Bar').locator('[data-ready="true"]')).toBeVisible()
    await p.show(kind)
    await panel.getByLabel('Import level', { exact: true }).setInputFiles(path)
    const confirmation = panel.getByRole('group', { name: 'Replace level confirmation', exact: true })
    await expect(confirmation).toContainText('2 steps')
    await expect(panel.locator('[data-piece-id]')).toHaveCount(0)
    await confirmation.getByRole('button', { name: 'Replace', exact: true }).click()
    await expect(controls.getByRole('button')).toHaveText(['Capture step', 'Update step', 'Second arrangement', 'First arrangement'])
    await expect.poll(() => snapshot(p, panel)).toEqual(second)
    await expect(panel.getByLabel('Value', { exact: true })).toHaveValue('5')
    await expect(panel.getByRole('textbox', { name: 'Prompt', exact: true })).toHaveValue('Second instruction.')
    await controls.getByRole('button', { name: 'First arrangement', exact: true }).click()
    await expect.poll(() => snapshot(p, panel)).toEqual(first)
    await expect(panel.getByLabel('Cells', { exact: true })).toHaveValue('2')
    await expect(panel.getByRole('textbox', { name: 'Prompt', exact: true })).toHaveValue('First instruction.\nExplain your answer.')
    // Later-step corruption must reject everything without changing metadata or scene.
    const corrupt = structuredClone(document)
    corrupt.steps[1]!.trains[0]!.anchor.x = 999
    await panel.getByLabel('Import level', { exact: true }).setInputFiles({ name: 'corrupt.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(corrupt)) })
    await expect(confirmation).toHaveCount(0)
    await expect(panel.getByRole('region', { name: 'Level files', exact: true })).toContainText('Step step-1:')
    await expect.poll(() => snapshot(p, panel)).toEqual(first)
    await expect(panel.getByLabel('Cells', { exact: true })).toHaveValue('2')
    const reexport = page.waitForEvent('download')
    await panel.getByRole('button', { name: 'Export level', exact: true }).click()
    const restoredDownload = await reexport
    const restoredPath = info.outputPath('restored.json'); await restoredDownload.saveAs(restoredPath)
    expect(JSON.parse(await readFile(restoredPath, 'utf8'))).toEqual(document)
    await p.add(kind, 'one')
    await capture.click()
    await expect(controls.getByRole('button', { name: 'Step 3', exact: true })).toBeVisible()
    const ids = await panel.locator('[data-piece-id]').evaluateAll(elements => elements.map(el => el.getAttribute('data-piece-id')))
    expect(new Set(ids).size).toBe(ids.length)
  })
}
test('file export resolves drafts and dirty choices; file selection and cancel preserve working scene', async ({ playground: p, page }, info) => {
  const panel = await p.show('Array')
  await p.add('Array', 'two')
  await panel.getByRole('button', { name: 'Export level', exact: true }).click()
  await expect(panel.getByRole('group', { name: 'Capture before export', exact: true })).toBeVisible()
  const initialDownload = page.waitForEvent('download')
  await panel.getByRole('button', { name: 'Capture first', exact: true }).click()
  const initial = await initialDownload; const path = info.outputPath('initial.json'); await initial.saveAs(path)
  await p.add('Array', 'three')
  const working = await snapshot(p, panel)
  await panel.getByRole('button', { name: 'Add condition', exact: true }).click()
  page.once('dialog', dialog => dialog.dismiss())
  await panel.getByRole('button', { name: 'Export level', exact: true }).click()
  await expect(panel.getByText('Unapplied goal draft', { exact: true })).toBeVisible()
  await panel.getByRole('button', { name: 'Apply goal', exact: true }).click()
  await panel.getByRole('button', { name: 'Export level', exact: true }).click()
  const dirty = panel.getByRole('group', { name: 'Export unsaved changes', exact: true })
  await dirty.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect.poll(() => snapshot(p, panel)).toEqual(working)
  await panel.getByRole('button', { name: 'Export level', exact: true }).click()
  const savedDownload = page.waitForEvent('download')
  await dirty.getByRole('button', { name: 'Export saved steps only', exact: true }).click()
  const saved = await savedDownload; const savedPath = info.outputPath('saved.json'); await saved.saveAs(savedPath)
  expect(levelDocumentSchema.parse(JSON.parse(await readFile(savedPath, 'utf8'))).steps[0]!.trains).toHaveLength(1)
  await expect.poll(() => snapshot(p, panel)).toEqual(working)
  await expect(panel.getByRole('button', { name: 'Update step', exact: true })).toBeEnabled()
  await panel.getByLabel('Import level', { exact: true }).setInputFiles(path)
  await expect.poll(() => snapshot(p, panel)).toEqual(working)
  await panel.getByRole('group', { name: 'Replace level confirmation', exact: true }).getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect.poll(() => snapshot(p, panel)).toEqual(working)
  await panel.getByRole('button', { name: 'Export level', exact: true }).click()
  const updatedDownload = page.waitForEvent('download')
  await dirty.getByRole('button', { name: 'Update step and export', exact: true }).click()
  const updated = await updatedDownload; const updatedPath = info.outputPath('updated.json'); await updated.saveAs(updatedPath)
  expect(levelDocumentSchema.parse(JSON.parse(await readFile(updatedPath, 'utf8'))).steps[0]!.trains).toHaveLength(2)
  await expect(panel.getByRole('button', { name: 'Update step', exact: true })).toBeDisabled()
})

test.describe('import during inertia', () => {
  test.use({ contextOptions: { reducedMotion: 'no-preference' }, reducedMotion: 'no-preference' })
  test('confirmed replacement cancels a throw with no delayed commit', async ({ playground: p, page }) => {
    const panel = await p.show('Bar')
    const rod = await p.add('Bar', 'six')
    const document = { version: 1, board: { kind: 'bar', config: { columns: 24, targetCount: 3 } }, steps: [{ id: 'step-10', title: 'Replacement', prompt: '', goal: null, trains: [{ id: 'train-90', anchor: { x: 0, y: 5 }, parts: [{ value: 2, offset: { x: 0, y: 0 }, orientation: 'horizontal' }] }] }] }
    await panel.getByLabel('Import level', { exact: true }).setInputFiles({ name: 'level.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(document)) })
    const replace = panel.getByRole('group', { name: 'Replace level confirmation', exact: true }).getByRole('button', { name: 'Replace', exact: true })
    await rod.scrollIntoViewIfNeeded()
    const face = await rod.locator('.face.top').boundingBox()
    if (!face) throw new Error('Missing rod face')
    const axes = await rod.evaluate(el => {
      const world = el.closest('[data-grid-world]')!
      const origin = world.querySelector('[data-grid-axis="origin"]')!.getBoundingClientRect()
      const x = world.querySelector('[data-grid-axis="x"]')!.getBoundingClientRect()
      return { x: x.left - origin.left, y: x.top - origin.top }
    })
    await page.mouse.move(face.x + face.width / 2, face.y + face.height / 2)
    await page.mouse.down()
    await page.mouse.move(face.x + face.width / 2 + axes.x * 10, face.y + face.height / 2 + axes.y * 10, { steps: 8 })
    await page.mouse.up()
    await expect.poll(async () => (await p.geometry(rod)).offset).toBeGreaterThan(0.05)
    // Keyboard activation avoids a pointer event elsewhere cancelling the throw first.
    await replace.focus(); await page.keyboard.press('Enter')
    const restored = panel.locator('[data-piece-id="train-90"]')
    await expect(restored).toBeVisible()
    const expected = await snapshot(p, panel)
    await page.waitForTimeout(1800)
    expect(await snapshot(p, panel)).toEqual(expected)
    await expect(rod).toHaveCount(0)
  })
})
