<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.6*" />
    <PackageReference Include="TUnit.AspNetCore" Version="1.65.63" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TsiaCoach.WebApi\TsiaCoach.WebApi.csproj" />
  </ItemGroup>

</Project>
